spring:
  profiles:
    active: jpa
  logging:
    level:
      org.springframework: debug
      com.github.cyberpunkperson.widgetorganizer: debug
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 10
          generate_statistics: true
    datasource:
      url: jdbc:h2:mem:order-cacheable
      driverClassName: org.h2.Driver
      username: ${sandbox.datasource.username}
      password: ${sandbox.datasource.password}
    h2:
      console:
        enabled: true